"""
Tests for HookManager — Git hooks lifecycle management.

Covers: HookConfig, HookManager (install/uninstall/status/list/run/config).
"""

import os

import pytest

from vibecollab.domain.hook_manager import HookConfig, HookManager

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def git_project(tmp_path):
    """Create a temporary project with .git/hooks directory."""
    git_dir = tmp_path / ".git"
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True)
    return tmp_path


@pytest.fixture
def non_git_project(tmp_path):
    """Create a temporary project WITHOUT .git directory."""
    return tmp_path


@pytest.fixture
def sample_config():
    """Sample hooks configuration matching project.yaml format."""
    return {
        "enabled": True,
        "rules": {
            "pre-commit": ["vibecollab check", "ruff check src/"],
            "pre-push": ["pytest tests/ -q"],
        },
    }


# ---------------------------------------------------------------------------
# HookConfig tests
# ---------------------------------------------------------------------------

class TestHookConfig:
    def test_defaults(self):
        cfg = HookConfig()
        assert cfg.commands == []
        assert cfg.enabled is True

    def test_explicit_fields(self):
        cfg = HookConfig(commands=["vibecollab check"], enabled=False)
        assert cfg.commands == ["vibecollab check"]
        assert cfg.enabled is False


# ---------------------------------------------------------------------------
# HookManager initialization
# ---------------------------------------------------------------------------

class TestHookManagerInit:
    def test_init_no_config(self, git_project):
        hm = HookManager(project_root=git_project)
        assert hm.enabled is True
        assert hm.config == {}
        assert hm.project_root == git_project

    def test_init_with_config(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        assert hm.enabled is True
        assert "pre-commit" in hm.config
        assert hm.config["pre-commit"].commands == [
            "vibecollab check", "ruff check src/"
        ]

    def test_init_disabled(self, git_project):
        config = {"enabled": False, "rules": {}}
        hm = HookManager(project_root=git_project, config=config)
        assert hm.enabled is False

    def test_load_config_dict_format(self, git_project):
        """Test loading rules in dict format (commands + enabled)."""
        config = {
            "enabled": True,
            "rules": {
                "pre-commit": {
                    "commands": ["vibecollab check"],
                    "enabled": False,
                },
            },
        }
        hm = HookManager(project_root=git_project, config=config)
        assert hm.config["pre-commit"].commands == ["vibecollab check"]
        assert hm.config["pre-commit"].enabled is False


# ---------------------------------------------------------------------------
# is_git_repo
# ---------------------------------------------------------------------------

class TestIsGitRepo:
    def test_git_repo(self, git_project):
        hm = HookManager(project_root=git_project)
        assert hm.is_git_repo() is True

    def test_non_git_repo(self, non_git_project):
        hm = HookManager(project_root=non_git_project)
        assert hm.is_git_repo() is False


# ---------------------------------------------------------------------------
# install
# ---------------------------------------------------------------------------

class TestInstall:
    def test_install_pre_commit(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        result = hm.install("pre-commit")
        assert result is True

        hook_path = git_project / ".git" / "hooks" / "pre-commit"
        assert hook_path.exists()
        content = hook_path.read_text(encoding="utf-8")
        assert "Generated by vibecollab" in content
        assert "pre-commit" in content

    def test_install_already_exists_no_force(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")
        result = hm.install("pre-commit", force=False)
        assert result is False

    def test_install_force_overwrite(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")
        result = hm.install("pre-commit", force=True)
        assert result is True

    def test_install_invalid_hook_type(self, git_project):
        hm = HookManager(project_root=git_project)
        result = hm.install("invalid-hook")
        assert result is False

    def test_install_not_git_repo(self, non_git_project):
        hm = HookManager(project_root=non_git_project)
        result = hm.install("pre-commit")
        assert result is False

    def test_install_uses_default_commands(self, git_project):
        """Install without config should use default commands."""
        hm = HookManager(project_root=git_project)
        hm.install("pre-commit")
        hook_path = git_project / ".git" / "hooks" / "pre-commit"
        content = hook_path.read_text(encoding="utf-8")
        assert "vibecollab check" in content

    def test_install_uses_config_commands(self, git_project, sample_config):
        """Install with config should use configured commands."""
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")
        hook_path = git_project / ".git" / "hooks" / "pre-commit"
        content = hook_path.read_text(encoding="utf-8")
        assert "ruff check" in content


# ---------------------------------------------------------------------------
# uninstall
# ---------------------------------------------------------------------------

class TestUninstall:
    def test_uninstall_vibecollab_hook(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")
        result = hm.uninstall("pre-commit")
        assert result is True
        assert not (git_project / ".git" / "hooks" / "pre-commit").exists()

    def test_uninstall_non_vibecollab_hook(self, git_project):
        """Should NOT remove hooks not generated by vibecollab."""
        hook_path = git_project / ".git" / "hooks" / "pre-commit"
        hook_path.write_text("#!/bin/bash\necho custom", encoding="utf-8")

        hm = HookManager(project_root=git_project)
        result = hm.uninstall("pre-commit")
        assert result is False
        assert hook_path.exists()

    def test_uninstall_nonexistent(self, git_project):
        hm = HookManager(project_root=git_project)
        result = hm.uninstall("pre-commit")
        assert result is False

    def test_uninstall_not_git_repo(self, non_git_project):
        hm = HookManager(project_root=non_git_project)
        result = hm.uninstall("pre-commit")
        assert result is False

    def test_uninstall_all(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")
        hm.install("pre-push")
        count = hm.uninstall_all()
        assert count == 2
        assert not (git_project / ".git" / "hooks" / "pre-commit").exists()
        assert not (git_project / ".git" / "hooks" / "pre-push").exists()

    def test_uninstall_all_none_installed(self, git_project):
        hm = HookManager(project_root=git_project)
        count = hm.uninstall_all()
        assert count == 0


# ---------------------------------------------------------------------------
# status
# ---------------------------------------------------------------------------

class TestStatus:
    def test_status_no_hooks(self, git_project):
        hm = HookManager(project_root=git_project)
        s = hm.status()
        assert s["is_git_repo"] is True
        assert s["enabled"] is True
        assert "pre-commit" in s["hooks"]
        assert s["hooks"]["pre-commit"]["installed"] is False

    def test_status_with_installed_hook(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")
        s = hm.status()
        assert s["hooks"]["pre-commit"]["installed"] is True
        assert s["hooks"]["pre-commit"]["is_vibecollab"] is True
        assert s["hooks"]["pre-commit"]["configured"] is True

    def test_status_not_git_repo(self, non_git_project):
        hm = HookManager(project_root=non_git_project)
        s = hm.status()
        assert s["is_git_repo"] is False
        assert s["hooks"] == {}


# ---------------------------------------------------------------------------
# list_hooks
# ---------------------------------------------------------------------------

class TestListHooks:
    def test_list_empty(self, git_project):
        hm = HookManager(project_root=git_project)
        assert hm.list_hooks() == []

    def test_list_installed(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")
        hm.install("pre-push")
        hooks = hm.list_hooks()
        assert "pre-commit" in hooks
        assert "pre-push" in hooks

    def test_list_not_git_repo(self, non_git_project):
        hm = HookManager(project_root=non_git_project)
        assert hm.list_hooks() == []

    def test_list_excludes_non_vibecollab(self, git_project, sample_config):
        """Custom hooks should not appear in list."""
        # Install vibecollab hook
        hm = HookManager(project_root=git_project, config=sample_config)
        hm.install("pre-commit")

        # Add custom hook
        custom_hook = git_project / ".git" / "hooks" / "post-commit"
        custom_hook.write_text("#!/bin/bash\necho custom", encoding="utf-8")

        hooks = hm.list_hooks()
        assert "pre-commit" in hooks
        assert "post-commit" not in hooks


# ---------------------------------------------------------------------------
# _get_commands
# ---------------------------------------------------------------------------

class TestGetCommands:
    def test_default_pre_commit(self, git_project):
        hm = HookManager(project_root=git_project)
        cmds = hm._get_commands("pre-commit")
        assert cmds == ["vibecollab check"]

    def test_default_pre_push(self, git_project):
        hm = HookManager(project_root=git_project)
        cmds = hm._get_commands("pre-push")
        assert cmds == ["pytest tests/ -q", "vibecollab check"]

    def test_config_overrides_default(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        cmds = hm._get_commands("pre-commit")
        assert cmds == ["vibecollab check", "ruff check src/"]

    def test_no_default_returns_empty(self, git_project):
        hm = HookManager(project_root=git_project)
        cmds = hm._get_commands("post-checkout")
        assert cmds == []


# ---------------------------------------------------------------------------
# _generate_script
# ---------------------------------------------------------------------------

class TestGenerateScript:
    def test_script_contains_commands(self, git_project, sample_config):
        hm = HookManager(project_root=git_project, config=sample_config)
        script = hm._generate_script("pre-commit", ["vibecollab check", "ruff check src/"])
        assert "Generated by vibecollab" in script
        assert "pre-commit" in script
        assert "vibecollab check" in script

    def test_script_platform_format(self, git_project):
        hm = HookManager(project_root=git_project)
        script = hm._generate_script("pre-commit", ["vibecollab check"])
        if os.name == "nt":
            assert "Write-Host" in script or "LASTEXITCODE" in script
        else:
            assert "#!/bin/bash" in script


# ---------------------------------------------------------------------------
# HOOK_TYPES constant
# ---------------------------------------------------------------------------

class TestHookTypes:
    def test_supported_types(self):
        assert "pre-commit" in HookManager.HOOK_TYPES
        assert "pre-push" in HookManager.HOOK_TYPES
        assert "post-commit" in HookManager.HOOK_TYPES
        assert "post-checkout" in HookManager.HOOK_TYPES
        assert "prepare-commit-msg" in HookManager.HOOK_TYPES
        assert len(HookManager.HOOK_TYPES) == 5
